### ISSUE TITLE
***// Edit Code Platform //***

### ISSUE THREAD

**Issue by Sivakornsir** [OnUr-KB/Project-16222#19]
[https://scratch.mit.edu/projects/888811436](url)

**Comment by OnUr-KB** [comment]
- [ ] ด่าน1 แท่นยืนแบบเดี่ยว(หิน)
- [ ] ด่าน2 แท่นยืนแบบเดี่ยว (ขอนไม้)
- [ ] ด่าน3 แท่นยืนแบบเดี่ยว(ก้อนเมฆ)
- [ ] ด่าน4 แท่นยืนแบบเดี่ยว(ดาวเคราะห์) + อุปสรรค(อุกาบาต)
